#!/usr/bin/env bash
# Turn ps5/plugins.txt into:
#   $out/static_modules.c  the vlc_static_modules[] table libvlc reads at startup
#   $out/link.rsp          the plugin archives, libvlc, libvlccore and their libraries
# Library dependencies come from each plugin's libtool .la file, as VLCKit does.
set -euo pipefail

here=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
target=${TARGET:-host}
work=${VLC_PS5_WORK:-$HOME/ps5/vlc-ps5}
build=$work/build-vlc-$target
prefix=$work/prefix-$target
out=${1:-$work/static-$target}
mods=$build/modules
mkdir -p "$out"

mapfile -t plugins < <(sed -e 's/#.*//' -e 's/[[:space:]]//g' "$here/plugins.txt" | grep -v '^$')

missing=()
for p in "${plugins[@]}"; do
    [[ -f $mods/.libs/lib${p}_plugin.a ]] || missing+=("$p")
done
if [[ ${#missing[@]} -gt 0 ]]; then
    echo "plugins not built: ${missing[*]}" >&2
    exit 1
fi

# The entry point's name is the module's MODULE_NAME, which is not always the file
# name (libpacketizer_h264_plugin.a defines vlc_entry__h264), so read it from the archive.
nm=${NM:-nm}
entries=()
for p in "${plugins[@]}"; do
    entry=$("$nm" -g --defined-only "$mods/.libs/lib${p}_plugin.a" |
        grep -oE 'vlc_entry__[A-Za-z0-9_]+$' | sort -u)
    if [[ $(wc -w <<<"$entry") -ne 1 ]]; then
        echo "lib${p}_plugin.a: expected one vlc_entry__*, found: ${entry:-none}" >&2
        exit 1
    fi
    entries+=("$entry")
done
# Plugins built with the app itself (APP_MODULES="vlc_entry__x ..."), first.
read -r -a app_modules <<<"${APP_MODULES:-}"
entries=("${app_modules[@]}" "${entries[@]}")

{
    echo "/* Generated by ps5/gen-static-modules.sh from ps5/plugins.txt. */"
    echo "#include <stddef.h>"
    echo "typedef int (*vlc_set_cb)(void *, void *, int, ...);"
    for e in "${entries[@]}"; do
        echo "int ${e}(vlc_set_cb, void *);"
    done
    echo "typedef int (*vlc_plugin_cb)(vlc_set_cb, void *);"
    echo "vlc_plugin_cb vlc_static_modules[] = {"
    for e in "${entries[@]}"; do
        echo "    ${e},"
    done
    echo "    NULL"
    echo "};"
} > "$out/static_modules.c"

# libtool's dependency_libs: '-L/x -lfoo /path/libbar.la ...'. Internal .la files
# become their archive; external flags pass through.
deps=()
add_la() {
    local la=$1 line item dir
    line=$(sed -n "s/^dependency_libs='\(.*\)'/\1/p" "$la")
    for item in $line; do
        case $item in
        *.la)
            # A build tree keeps the archive in .libs/; an installed .la sits beside it.
            dir=$(dirname "$item")
            if [[ -f $dir/.libs/$(basename "${item%.la}").a ]]; then
                deps+=("$dir/.libs/$(basename "${item%.la}").a")
            else
                deps+=("${item%.la}.a")
            fi
            add_la "$item"
            ;;
        *) deps+=("$item") ;;
        esac
    done
}

{
    echo "--start-group"
    for p in "${plugins[@]}"; do
        echo "$mods/.libs/lib${p}_plugin.a"
        add_la "$mods/lib${p}_plugin.la"
    done
    echo "$build/lib/.libs/libvlc.a"
    echo "$build/src/.libs/libvlccore.a"
    add_la "$build/src/libvlccore.la"
    # Keep the first appearance of each item: archives stay in the group.
    printf '%s\n' "${deps[@]}" | grep -v -- '^-L' | awk '!seen[$0]++'
    # FFmpeg's Opus decoder needs libswresample, which VLC's configure (run
    # before it was built) doesn't list.
    [[ -f $prefix/lib/libswresample.a ]] && echo "-lswresample"
    echo "--end-group"
} > "$out/link.rsp.tmp"
# Wrap linker-only flags for the compiler driver.
sed -e 's/^--start-group$/-Wl,--start-group/' -e 's/^--end-group$/-Wl,--end-group/' \
    "$out/link.rsp.tmp" > "$out/link.rsp"
rm -f "$out/link.rsp.tmp"
echo "-L$prefix/lib" >> "$out/link.rsp"

echo "${#plugins[@]} plugins -> $out/static_modules.c, $out/link.rsp"
